-ifndef(__MODBUS_HRL__).
-define(__MODBUS_HRL__, true).

-define(READ_DISCRETE_INPUTS, 2).
-define(READ_COILS, 1).
-define(WRITE_SINGLE_COIL, 5).
-define(WRITE_MULTIPLE_COILS, 15).
-define(READ_INPUT_REGISTERS, 4).
-define(READ_HOLDING_REGISTERS, 3).
-define(WRITE_SINGLE_HOLDING_REGISTER, 6).
-define(WRITE_MULTIPLE_HOLDING_REGISTERS, 16).

-define(ILLEGAL_FUNCTION, 1).
-define(ILLEGAL_DATA_ADDRESS, 2).
-define(ILLEGAL_DATA_VALUE, 3).
-define(SLAVE_DEVICE_FAILURE, 4).
-define(ACKNOWLEDGE, 5).
-define(SLAVE_DEVICE_BUSY, 6).
-define(NEGATIVE_ACKNOWLEDGE, 7).
-define(MEMORY_PARITY_ERROR, 8).
-define(GATEWAY_PATH_UNAVAILABLE, 10).
-define(GATEWAY_TARGET_DEVICE_FAILED_TO_RESPOND, 11).

-endif.
